# Generated by Django 2.2.1 on 2021-12-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.IntegerField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
                ('Departmentmail', models.EmailField(max_length=254)),
                ('Departmentsection', models.CharField(max_length=120)),
                ('Departmentdetails', models.TextField()),
                ('DepartmentType', models.TextField()),
            ],
        ),
    ]
